# Generated by Django 4.1.3 on 2023-11-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takvim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik_tr', models.CharField(blank=True, max_length=100)),
                ('baslik_ku', models.CharField(blank=True, max_length=100)),
                ('baslik_en', models.CharField(blank=True, max_length=100)),
                ('metin_tr', models.TextField(blank=True)),
                ('metin_ku', models.TextField(blank=True)),
                ('metin_en', models.TextField(blank=True)),
                ('foto_tr', models.ImageField(upload_to='takvim/tr')),
                ('foto_kr', models.ImageField(upload_to='takvim/kr')),
                ('foto_en', models.ImageField(upload_to='takvim/en')),
            ],
        ),
    ]
