# Generated by Django 4.1.3 on 2023-11-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0002_takvim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takvim',
            old_name='foto_kr',
            new_name='foto_ku',
        ),
    ]
