# Generated by Django 4.1.3 on 2023-11-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0003_rename_foto_kr_takvim_foto_ku'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide_index',
            name='redirect_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
