# Generated by Django 4.1.3 on 2023-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0004_slide_index_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide_index',
            name='redirect_url',
            field=models.URLField(blank=True),
        ),
    ]
