# Generated by Django 4.1.3 on 2023-11-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0005_alter_slide_index_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vitrin_arkasi_rengi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
