# Generated by Django 4.1.3 on 2023-11-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0006_settings_vitrin_arkasi_rengi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proje_etkinlik',
            old_name='active_anasayfa',
            new_name='active_vitrin',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='vitrin_arkasi_rengi',
        ),
    ]
