# Generated by Django 4.1.3 on 2023-11-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0007_rename_active_anasayfa_proje_etkinlik_active_vitrin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program_etkinlik',
            old_name='active_anasayfa',
            new_name='active_vitrin',
        ),
    ]
