# Generated by Django 4.1.3 on 2023-11-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0008_rename_active_anasayfa_program_etkinlik_active_vitrin'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vitrin_arkasi_rengi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
