# Generated by Django 4.1.3 on 2023-11-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0009_settings_vitrin_arkasi_rengi'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='isbirlikleri_foto',
            field=models.ImageField(blank=True, upload_to='genel/isbirlikleri'),
        ),
    ]
