# Generated by Django 4.1.3 on 2023-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0010_settings_isbirlikleri_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='isbirlikleri_foto',
            new_name='isbirlikleri_foto_en',
        ),
        migrations.AddField(
            model_name='settings',
            name='isbirlikleri_foto_ku',
            field=models.ImageField(blank=True, upload_to='genel/isbirlikleri'),
        ),
        migrations.AddField(
            model_name='settings',
            name='isbirlikleri_foto_tr',
            field=models.ImageField(blank=True, upload_to='genel/isbirlikleri'),
        ),
    ]
