# Generated by Django 4.1.3 on 2023-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0011_rename_isbirlikleri_foto_settings_isbirlikleri_foto_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev_yayıncılık',
            name='baslik_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ev_yayıncılık',
            name='baslik_ku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ev_yayıncılık',
            name='foto',
            field=models.ImageField(upload_to='ev_yayıncılık/foto'),
        ),
    ]
