# Generated by Django 4.1.3 on 2023-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wejegeh', '0012_alter_ev_yayıncılık_baslik_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='isbirlikleri_name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='isbirlikleri_name_ku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='isbirlikleri_name_tr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
